spring.application.name=tauche
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:tauche}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.address=0.0.0.0